version: '3'
services:
  core:
    container_name: "core"
    build: core/.
    network_mode: host
    ports:
      - "8080:8080"
  client:
    container_name: "client"
    build: client/.
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - './client:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true