apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
          limits:
            cpu: "500m"
# kind: Deployment
# ...
# metadata:
#   name: nginx
#   labels:          
# // This is a label for the deployment. The deployment is identified 
# // by this label only.
#     app: nginx
#     tier: backend
# spec:
#   selector:
# // If we make some changes in the deployment template or from cli, 
# // for eg: kubectl scale --replicas=3 deploy/nginx, it will identify 
# // rest 2 replicas(out of 5) to terminate them with the use of 
# // selector.
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:    
# // This is a label is applied to the pods when the deployment 
# // deploys the pods. For eg: IF we have 5 pods derived by this deployment, 
# // all pods will the same labels.
#         app: nginx
#         tier: backend...

